### ISSUE TITLE
Cannot build on Rust 1.43.0

### ISSUE THREAD

**Issue by D4nte** [therustmonk/mixin#1]
Getting the following error when trying to build on Rust 1.43.0 (dependency brought in by yewtify).

```
wasm-pack build --debug --target web --out-name wasm --out-dir ./static
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling pkg-config v0.3.17
   Compiling unicode-segmentation v1.6.0
   Compiling yew v0.15.0 (ssh://git@github.com/yewstack/yew?branch=push-if#89eb1840)
   Compiling once_cell v1.3.1
   Compiling num_cpus v1.13.0
   Compiling yew-macro v0.15.0 (ssh://git@github.com/yewstack/yew?branch=push-if#89eb1840)
   Compiling mixin v0.2.0
error[E0599]: no method named `as_dyn_error` found for reference `&proc_macro::LexError` in the current scope
  --> /Users/froyer/.cargo/registry/src/github.com-1ecc6299db9ec823/mixin-0.2.0/src/lib.rs:10:10
   |
10 |   #[derive(Error, Debug)]
   |            ^^^^^ method not found in `&proc_macro::LexError`
   |
   = note: the method `as_dyn_error` exists but the following trait bounds were not satisfied:
           `proc_macro::LexError: std::error::Error`
           which is required by `proc_macro::LexError: thiserror::aserror::AsDynError`
           `&proc_macro::LexError: std::error::Error`
           which is required by `&proc_macro::LexError: thiserror::aserror::AsDynError`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `as_display` found for reference `&proc_macro::LexError` in the current scope
  --> /Users/froyer/.cargo/registry/src/github.com-1ecc6299db9ec823/mixin-0.2.0/src/lib.rs:20:13
   |
20 |       #[error("lex error: {0}")]
   |               ^^^^^^^^^^^^^^^^ method not found in `&proc_macro::LexError`
   |
   = note: the method `as_display` exists but the following trait bounds were not satisfied:
           `proc_macro::LexError: std::fmt::Display`
           which is required by `&proc_macro::LexError: thiserror::display::DisplayAsDisplay`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `mixin`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
  full command: "cargo" "build" "--lib" "--target" "wasm32-unknown-unknown"
make: *** [build] Error 1

Process finished with exit code 2
```

**Comment by D4nte** [comment]
Please note same issue occurs on nightly-2020-01-15.

**Comment by D4nte** [comment]
Ok I see, it needs `LexError` to implement `std::error::Error` which only happened here: https://github.com/rust-lang/rust/commit/c0c526951c87c79e0db5e6e32b95bbe0a01347d3#diff-9ea37887c69f218bed1798983de82b79 so the RMV is `nightly-2020-02-08` or 9.
